// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AppendActivityEventReducer from "../append_activity_event_reducer";
import ConfirmMappingsReducer from "../confirm_mappings_reducer";
import DeleteRecordReducer from "../delete_record_reducer";
import InsertLeadRecordsReducer from "../insert_lead_records_reducer";
import ProcessCsvUploadReducer from "../process_csv_upload_reducer";
import RecordDataQualityReportReducer from "../record_data_quality_report_reducer";
import RecordMappingSuggestionsReducer from "../record_mapping_suggestions_reducer";
import RegisterUploadReducer from "../register_upload_reducer";
import StageCsvUploadReducer from "../stage_csv_upload_reducer";
import UpdateJobProgressReducer from "../update_job_progress_reducer";

export type AppendActivityEventParams = __Infer<typeof AppendActivityEventReducer>;
export type ConfirmMappingsParams = __Infer<typeof ConfirmMappingsReducer>;
export type DeleteRecordParams = __Infer<typeof DeleteRecordReducer>;
export type InsertLeadRecordsParams = __Infer<typeof InsertLeadRecordsReducer>;
export type ProcessCsvUploadParams = __Infer<typeof ProcessCsvUploadReducer>;
export type RecordDataQualityReportParams = __Infer<typeof RecordDataQualityReportReducer>;
export type RecordMappingSuggestionsParams = __Infer<typeof RecordMappingSuggestionsReducer>;
export type RegisterUploadParams = __Infer<typeof RegisterUploadReducer>;
export type StageCsvUploadParams = __Infer<typeof StageCsvUploadReducer>;
export type UpdateJobProgressParams = __Infer<typeof UpdateJobProgressReducer>;

