// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
t as __t
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  timestamp: __t.timestamp(),
  action: __t.string(),
  entityType: __t.string().name("entity_type"),
  entityId: __t.option(__t.string()).name("entity_id"),
  detailsJson: __t.option(__t.string()).name("details_json"),
  userId: __t.option(__t.string()).name("user_id"),
  status: __t.option(__t.string()),
  durationMs: __t.option(__t.u64()).name("duration_ms"),
  emittedBy: __t.identity().name("emitted_by"),
});
