// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
t as __t
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  fileId: __t.string().name("file_id"),
  sourceColumn: __t.string().name("source_column"),
  targetColumn: __t.string().name("target_column"),
  confidence: __t.f64(),
  confirmedAt: __t.timestamp().name("confirmed_at"),
  confirmedBy: __t.identity().name("confirmed_by"),
});
