// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
t as __t
} from "spacetimedb";

import {
ColumnMappingInput,
} from "./types";

export default {
  fileId: __t.string(),
  get mappings() {
    return __t.array(ColumnMappingInput);
  },
  jobId: __t.option(__t.string()),
  batchId: __t.option(__t.string()),
};
