// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
t as __t
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  businessName: __t.option(__t.string()).name("business_name"),
  firstName: __t.option(__t.string()).name("first_name"),
  lastName: __t.option(__t.string()).name("last_name"),
  address: __t.option(__t.string()),
  city: __t.option(__t.string()),
  state: __t.option(__t.string()),
  zipCode: __t.option(__t.string()).name("zip_code"),
  country: __t.option(__t.string()),
  phone: __t.option(__t.string()),
  email: __t.option(__t.string()),
  additionalEmails: __t.option(__t.string()).name("additional_emails"),
  additionalPhones: __t.option(__t.string()).name("additional_phones"),
  website: __t.option(__t.string()),
  industry: __t.option(__t.string()),
  employeeCount: __t.option(__t.u32()).name("employee_count"),
  annualRevenue: __t.option(__t.f64()).name("annual_revenue"),
  foundedYear: __t.option(__t.u32()).name("founded_year"),
  description: __t.option(__t.string()),
  contactName: __t.option(__t.string()).name("contact_name"),
  contactTitle: __t.option(__t.string()).name("contact_title"),
  additionalDataJson: __t.option(__t.string()).name("additional_data_json"),
  sourceFile: __t.option(__t.string()).name("source_file"),
  datasetId: __t.option(__t.string()).name("dataset_id"),
  leadCategory: __t.option(__t.string()).name("lead_category"),
  batchId: __t.option(__t.string()).name("batch_id"),
  qualityScore: __t.option(__t.f64()).name("quality_score"),
  createdAt: __t.timestamp().name("created_at"),
  updatedAt: __t.timestamp().name("updated_at"),
});
