// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
t as __t
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  fileId: __t.string().name("file_id"),
  overallScore: __t.f64().name("overall_score"),
  issuesJson: __t.string().name("issues_json"),
  duplicatesJson: __t.string().name("duplicates_json"),
  anomaliesJson: __t.string().name("anomalies_json"),
  suggestions: __t.array(__t.string()),
  createdAt: __t.timestamp().name("created_at"),
  createdBy: __t.identity().name("created_by"),
});
