// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.2.0 (commit eb11e2f5c41dce6979715ad407996270d61329f6).

/* eslint-disable */
/* tslint:disable */
import {
DbConnectionBuilder as __DbConnectionBuilder,
DbConnectionImpl as __DbConnectionImpl,
SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
convertToAccessorMap as __convertToAccessorMap,
makeQueryBuilder as __makeQueryBuilder,
procedures as __procedures,
reducerSchema as __reducerSchema,
reducers as __reducers,
schema as __schema,
table as __table,
type DbConnectionConfig as __DbConnectionConfig,
type ErrorContextInterface as __ErrorContextInterface,
type EventContextInterface as __EventContextInterface,
type QueryBuilder as __QueryBuilder,
type ReducerEventContextInterface as __ReducerEventContextInterface,
type RemoteModule as __RemoteModule,
type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
type SubscriptionHandleImpl as __SubscriptionHandleImpl
} from "spacetimedb";

// Import all reducer arg schemas
import AppendActivityEventReducer from "./append_activity_event_reducer";
import ConfirmMappingsReducer from "./confirm_mappings_reducer";
import DeleteRecordReducer from "./delete_record_reducer";
import InsertLeadRecordsReducer from "./insert_lead_records_reducer";
import ProcessCsvUploadReducer from "./process_csv_upload_reducer";
import RecordDataQualityReportReducer from "./record_data_quality_report_reducer";
import RecordMappingSuggestionsReducer from "./record_mapping_suggestions_reducer";
import RegisterUploadReducer from "./register_upload_reducer";
import StageCsvUploadReducer from "./stage_csv_upload_reducer";
import UpdateJobProgressReducer from "./update_job_progress_reducer";

// Import all procedure arg schemas

// Import all table schema definitions
import ActivityEventsRow from "./activity_events_table";
import ColumnMappingsRow from "./column_mappings_table";
import DataQualityReportsRow from "./data_quality_reports_table";
import DataRecordsRow from "./data_records_table";
import MappingSuggestionsRow from "./mapping_suggestions_table";
import ProcessingJobsRow from "./processing_jobs_table";
import UploadedFilesRow from "./uploaded_files_table";

/** Type-only namespace exports for generated type groups. */

/** The schema information for all tables in this module. This is defined the same was as the tables would have been defined in the server. */
const tablesSchema = __schema({
  activity_events: __table({
    name: 'activity_events',
    indexes: [
      { accessor: 'action', name: 'activity_events_action_idx_btree', algorithm: 'btree', columns: [
        'action',
      ] },
      { accessor: 'entity_type', name: 'activity_events_entity_type_idx_btree', algorithm: 'btree', columns: [
        'entityType',
      ] },
      { accessor: 'id', name: 'activity_events_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'activity_events_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ActivityEventsRow),
  column_mappings: __table({
    name: 'column_mappings',
    indexes: [
      { accessor: 'file_id', name: 'column_mappings_file_id_idx_btree', algorithm: 'btree', columns: [
        'fileId',
      ] },
      { accessor: 'id', name: 'column_mappings_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'column_mappings_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ColumnMappingsRow),
  data_quality_reports: __table({
    name: 'data_quality_reports',
    indexes: [
      { accessor: 'file_id', name: 'data_quality_reports_file_id_idx_btree', algorithm: 'btree', columns: [
        'fileId',
      ] },
      { accessor: 'id', name: 'data_quality_reports_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'data_quality_reports_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, DataQualityReportsRow),
  data_records: __table({
    name: 'data_records',
    indexes: [
      { accessor: 'id', name: 'data_records_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'data_records_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, DataRecordsRow),
  mapping_suggestions: __table({
    name: 'mapping_suggestions',
    indexes: [
      { accessor: 'file_id', name: 'mapping_suggestions_file_id_idx_btree', algorithm: 'btree', columns: [
        'fileId',
      ] },
      { accessor: 'id', name: 'mapping_suggestions_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'mapping_suggestions_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, MappingSuggestionsRow),
  processing_jobs: __table({
    name: 'processing_jobs',
    indexes: [
      { accessor: 'file_id', name: 'processing_jobs_file_id_idx_btree', algorithm: 'btree', columns: [
        'fileId',
      ] },
      { accessor: 'id', name: 'processing_jobs_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'status', name: 'processing_jobs_status_idx_btree', algorithm: 'btree', columns: [
        'status',
      ] },
    ],
    constraints: [
      { name: 'processing_jobs_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ProcessingJobsRow),
  uploaded_files: __table({
    name: 'uploaded_files',
    indexes: [
      { accessor: 'id', name: 'uploaded_files_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'status', name: 'uploaded_files_status_idx_btree', algorithm: 'btree', columns: [
        'status',
      ] },
    ],
    constraints: [
      { name: 'uploaded_files_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, UploadedFilesRow),
});

/** The schema information for all reducers in this module. This is defined the same way as the reducers would have been defined in the server, except the body of the reducer is omitted in code generation. */
const reducersSchema = __reducers(
  __reducerSchema("append_activity_event", AppendActivityEventReducer),
  __reducerSchema("confirm_mappings", ConfirmMappingsReducer),
  __reducerSchema("delete_record", DeleteRecordReducer),
  __reducerSchema("insert_lead_records", InsertLeadRecordsReducer),
  __reducerSchema("process_csv_upload", ProcessCsvUploadReducer),
  __reducerSchema("record_data_quality_report", RecordDataQualityReportReducer),
  __reducerSchema("record_mapping_suggestions", RecordMappingSuggestionsReducer),
  __reducerSchema("register_upload", RegisterUploadReducer),
  __reducerSchema("stage_csv_upload", StageCsvUploadReducer),
  __reducerSchema("update_job_progress", UpdateJobProgressReducer),
);

/** The schema information for all procedures in this module. This is defined the same way as the procedures would have been defined in the server. */
const proceduresSchema = __procedures(
);

/** The remote SpacetimeDB module schema, both runtime and type information. */
const REMOTE_MODULE = {
  versionInfo: {
    cliVersion: "2.2.0" as const,
  },
  tables: tablesSchema.schemaType.tables,
  reducers: reducersSchema.reducersType.reducers,
  ...proceduresSchema,
} satisfies __RemoteModule<
  typeof tablesSchema.schemaType,
  typeof reducersSchema.reducersType,
  typeof proceduresSchema
>;

/** The tables available in this remote SpacetimeDB module. Each table reference doubles as a query builder. */
export const tables: __QueryBuilder<typeof tablesSchema.schemaType> = __makeQueryBuilder(tablesSchema.schemaType);

/** The reducers available in this remote SpacetimeDB module. */
export const reducers = __convertToAccessorMap(reducersSchema.reducersType.reducers);

/** The procedures available in this remote SpacetimeDB module. */
export const procedures = __convertToAccessorMap(proceduresSchema.procedures);

/** The context type returned in callbacks for all possible events. */
export type EventContext = __EventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for reducer events. */
export type ReducerEventContext = __ReducerEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for subscription events. */
export type SubscriptionEventContext = __SubscriptionEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for error events. */
export type ErrorContext = __ErrorContextInterface<typeof REMOTE_MODULE>;
/** The subscription handle type to manage active subscriptions created from a {@link SubscriptionBuilder}. */
export type SubscriptionHandle = __SubscriptionHandleImpl<typeof REMOTE_MODULE>;

/** Builder class to configure a new subscription to the remote SpacetimeDB instance. */
export class SubscriptionBuilder extends __SubscriptionBuilderImpl<typeof REMOTE_MODULE> {}

/** Builder class to configure a new database connection to the remote SpacetimeDB instance. */
export class DbConnectionBuilder extends __DbConnectionBuilder<DbConnection> {}

/** The typed database connection to manage connections to the remote SpacetimeDB instance. This class has type information specific to the generated module. */
export class DbConnection extends __DbConnectionImpl<typeof REMOTE_MODULE> {
  /** Creates a new {@link DbConnectionBuilder} to configure and connect to the remote SpacetimeDB instance. */
  static builder = (): DbConnectionBuilder => {
    return new DbConnectionBuilder(REMOTE_MODULE, (config: __DbConnectionConfig<typeof REMOTE_MODULE>) => new DbConnection(config));
  };

  /** Creates a new {@link SubscriptionBuilder} to configure a subscription to the remote SpacetimeDB instance. */
  override subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  };
}

