// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
t as __t
} from "spacetimedb";

import {
LeadRecordInput,
} from "./types";

export default {
  fileId: __t.string(),
  batchId: __t.option(__t.string()),
  get records() {
    return __t.array(LeadRecordInput);
  },
};
