// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
t as __t
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  fileId: __t.string().name("file_id"),
  sourceColumn: __t.string().name("source_column"),
  suggestedTargetColumn: __t.option(__t.string()).name("suggested_target_column"),
  confidence: __t.f64(),
  rationale: __t.option(__t.string()),
  createdAt: __t.timestamp().name("created_at"),
  createdBy: __t.identity().name("created_by"),
});
