// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
t as __t
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  status: __t.string(),
  progress: __t.u32(),
  fileId: __t.string().name("file_id"),
  filePath: __t.string().name("file_path"),
  batchId: __t.option(__t.string()).name("batch_id"),
  processedRows: __t.option(__t.u64()).name("processed_rows"),
  totalRows: __t.option(__t.u64()).name("total_rows"),
  error: __t.option(__t.string()),
  createdAt: __t.timestamp().name("created_at"),
  updatedAt: __t.timestamp().name("updated_at"),
});
