// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
t as __t,
type Infer as __Infer
} from "spacetimedb";

export const ActivityEvent = __t.object("ActivityEvent", {
  id: __t.u64(),
  timestamp: __t.timestamp(),
  action: __t.string(),
  entityType: __t.string(),
  entityId: __t.option(__t.string()),
  detailsJson: __t.option(__t.string()),
  userId: __t.option(__t.string()),
  status: __t.option(__t.string()),
  durationMs: __t.option(__t.u64()),
  emittedBy: __t.identity(),
});
export type ActivityEvent = __Infer<typeof ActivityEvent>;

export const ActivityEventInput = __t.object("ActivityEventInput", {
  action: __t.string(),
  entityType: __t.string(),
  entityId: __t.option(__t.string()),
  detailsJson: __t.option(__t.string()),
  userId: __t.option(__t.string()),
  status: __t.option(__t.string()),
  durationMs: __t.option(__t.u64()),
});
export type ActivityEventInput = __Infer<typeof ActivityEventInput>;

export const ColumnMapping = __t.object("ColumnMapping", {
  id: __t.string(),
  fileId: __t.string(),
  sourceColumn: __t.string(),
  targetColumn: __t.string(),
  confidence: __t.f64(),
  confirmedAt: __t.timestamp(),
  confirmedBy: __t.identity(),
});
export type ColumnMapping = __Infer<typeof ColumnMapping>;

export const ColumnMappingInput = __t.object("ColumnMappingInput", {
  sourceColumn: __t.string(),
  targetColumn: __t.string(),
  confidence: __t.f64(),
});
export type ColumnMappingInput = __Infer<typeof ColumnMappingInput>;

export const DataQualityReport = __t.object("DataQualityReport", {
  id: __t.u64(),
  fileId: __t.string(),
  overallScore: __t.f64(),
  issuesJson: __t.string(),
  duplicatesJson: __t.string(),
  anomaliesJson: __t.string(),
  suggestions: __t.array(__t.string()),
  createdAt: __t.timestamp(),
  createdBy: __t.identity(),
});
export type DataQualityReport = __Infer<typeof DataQualityReport>;

export const DataQualityReportInput = __t.object("DataQualityReportInput", {
  fileId: __t.string(),
  overallScore: __t.f64(),
  issuesJson: __t.string(),
  duplicatesJson: __t.string(),
  anomaliesJson: __t.string(),
  suggestions: __t.array(__t.string()),
});
export type DataQualityReportInput = __Infer<typeof DataQualityReportInput>;

export const DataRecord = __t.object("DataRecord", {
  id: __t.string(),
  businessName: __t.option(__t.string()),
  firstName: __t.option(__t.string()),
  lastName: __t.option(__t.string()),
  address: __t.option(__t.string()),
  city: __t.option(__t.string()),
  state: __t.option(__t.string()),
  zipCode: __t.option(__t.string()),
  country: __t.option(__t.string()),
  phone: __t.option(__t.string()),
  email: __t.option(__t.string()),
  additionalEmails: __t.option(__t.string()),
  additionalPhones: __t.option(__t.string()),
  website: __t.option(__t.string()),
  industry: __t.option(__t.string()),
  employeeCount: __t.option(__t.u32()),
  annualRevenue: __t.option(__t.f64()),
  foundedYear: __t.option(__t.u32()),
  description: __t.option(__t.string()),
  contactName: __t.option(__t.string()),
  contactTitle: __t.option(__t.string()),
  additionalDataJson: __t.option(__t.string()),
  sourceFile: __t.option(__t.string()),
  datasetId: __t.option(__t.string()),
  leadCategory: __t.option(__t.string()),
  batchId: __t.option(__t.string()),
  qualityScore: __t.option(__t.f64()),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type DataRecord = __Infer<typeof DataRecord>;

export const LeadRecordInput = __t.object("LeadRecordInput", {
  id: __t.string(),
  businessName: __t.option(__t.string()),
  firstName: __t.option(__t.string()),
  lastName: __t.option(__t.string()),
  address: __t.option(__t.string()),
  city: __t.option(__t.string()),
  state: __t.option(__t.string()),
  zipCode: __t.option(__t.string()),
  country: __t.option(__t.string()),
  phone: __t.option(__t.string()),
  email: __t.option(__t.string()),
  additionalEmails: __t.option(__t.string()),
  additionalPhones: __t.option(__t.string()),
  website: __t.option(__t.string()),
  industry: __t.option(__t.string()),
  employeeCount: __t.option(__t.u32()),
  annualRevenue: __t.option(__t.f64()),
  foundedYear: __t.option(__t.u32()),
  description: __t.option(__t.string()),
  contactName: __t.option(__t.string()),
  contactTitle: __t.option(__t.string()),
  additionalDataJson: __t.option(__t.string()),
  datasetId: __t.option(__t.string()),
  leadCategory: __t.option(__t.string()),
  qualityScore: __t.option(__t.f64()),
});
export type LeadRecordInput = __Infer<typeof LeadRecordInput>;

export const MappingSuggestion = __t.object("MappingSuggestion", {
  id: __t.u64(),
  fileId: __t.string(),
  sourceColumn: __t.string(),
  suggestedTargetColumn: __t.option(__t.string()),
  confidence: __t.f64(),
  rationale: __t.option(__t.string()),
  createdAt: __t.timestamp(),
  createdBy: __t.identity(),
});
export type MappingSuggestion = __Infer<typeof MappingSuggestion>;

export const MappingSuggestionInput = __t.object("MappingSuggestionInput", {
  sourceColumn: __t.string(),
  suggestedTargetColumn: __t.option(__t.string()),
  confidence: __t.f64(),
  rationale: __t.option(__t.string()),
});
export type MappingSuggestionInput = __Infer<typeof MappingSuggestionInput>;

export const ProcessingJob = __t.object("ProcessingJob", {
  id: __t.string(),
  status: __t.string(),
  progress: __t.u32(),
  fileId: __t.string(),
  filePath: __t.string(),
  batchId: __t.option(__t.string()),
  processedRows: __t.option(__t.u64()),
  totalRows: __t.option(__t.u64()),
  error: __t.option(__t.string()),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type ProcessingJob = __Infer<typeof ProcessingJob>;

export const UploadRegistration = __t.object("UploadRegistration", {
  id: __t.string(),
  filename: __t.string(),
  originalName: __t.string(),
  size: __t.u64(),
  status: __t.option(__t.string()),
  headers: __t.array(__t.string()),
  recordCount: __t.option(__t.u64()),
  tags: __t.array(__t.string()),
  category: __t.option(__t.string()),
  qualityScore: __t.option(__t.f64()),
  datasetId: __t.option(__t.string()),
});
export type UploadRegistration = __Infer<typeof UploadRegistration>;

export const UploadedFile = __t.object("UploadedFile", {
  id: __t.string(),
  filename: __t.string(),
  originalName: __t.string(),
  size: __t.u64(),
  status: __t.string(),
  headers: __t.array(__t.string()),
  recordCount: __t.option(__t.u64()),
  tags: __t.array(__t.string()),
  category: __t.option(__t.string()),
  qualityScore: __t.option(__t.f64()),
  datasetId: __t.option(__t.string()),
  uploadedAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
  uploadedBy: __t.identity(),
});
export type UploadedFile = __Infer<typeof UploadedFile>;

