// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
t as __t
} from "spacetimedb";

export default {
  jobId: __t.string(),
  status: __t.string(),
  progress: __t.u32(),
  processedRows: __t.option(__t.u64()),
  totalRows: __t.option(__t.u64()),
  error: __t.option(__t.string()),
};
