// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
t as __t
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  filename: __t.string(),
  originalName: __t.string().name("original_name"),
  size: __t.u64(),
  status: __t.string(),
  headers: __t.array(__t.string()),
  recordCount: __t.option(__t.u64()).name("record_count"),
  tags: __t.array(__t.string()),
  category: __t.option(__t.string()),
  qualityScore: __t.option(__t.f64()).name("quality_score"),
  datasetId: __t.option(__t.string()).name("dataset_id"),
  uploadedAt: __t.timestamp().name("uploaded_at"),
  updatedAt: __t.timestamp().name("updated_at"),
  uploadedBy: __t.identity().name("uploaded_by"),
});
